---
title: "Tidying datas"
author: "Mael Elegoet"
date: '2022-06-17'
output: html_document
---

```{r loading packages}

library(tidyverse)
library(janitor) # install.packages("janitor")
library(here)
library(stringr)
library(readxl)
library(skimr)

```

```{r}

inverts <- read_excel(here("data", "inverts.xlsx"))

inverts_long <- inverts %>% pivot_longer(cols = c("2016","2017","2018"), names_to = "year",
                                         values_to = "sp_count") %>% 
    mutate(year = as.numeric(year))

inverts %>% select(common_name) %>% unique()

inverts_long

inverts_wide <- inverts_long %>% pivot_wider(names_from = common_name, values_from = sp_count )

inverts_wide <- inverts_wide %>% clean_names()

inverts_unite <- inverts_long %>% 
    unite(col = "site_year", c(site,year))

inverts_moyr <- inverts_long %>% unite(col = "moy_yr", c("month","year"), sep = "/")
inverts_moyr

inverts_triple_unite <- inverts_long %>% unite(col = "year_site_name", c("year","site","common_name"), sep = "-")
inverts_triple_unite

inverts_sep <- inverts_unite %>% separate(site_year, into = c("site","year"), sep ="_")

inverts

ca_abbr <- inverts %>% mutate(common_name = str_replace(common_name, "california", "CA"))
ca_abbr

```

