---
title: "Creating graphs in R with `ggplot2`"
author: "Mael Elegoet"
date: '2022-06-15'
output: html_document
---
# Plots with ggplot2

We are going to make plots in R and it's going to be amazing.




```{r}

library(tidyverse)
library(readxl)
library(readr)
library(here)

```

```{r}

ca_np <- read_csv(here("data", "ca_np.csv"))
names(ca_np)
head(ca_np)
summary(ca_np)
ci_np <- read_excel(here("data", "ci_np.xlsx"))

ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_line()

gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))






gg_base +
  geom_point()

gg_base +
  geom_col()

gg_base +  
  geom_area()

gg_base +
  geom_line(
    color = "red", 
    linetype = "dashed"
  )

gg_base + 
  geom_point(color = "purple",
             pch = 17,
             size = 4,
             alpha = 0.2)

gg_base + 
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  )

gg_base + 
  geom_col(aes(fill = visitors))

gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))


gg_np +
  geom_line(show.legend = FALSE) +
  theme_light() + 
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)
ggplot(data = ca_np, aes(x = year, y = visitors)) +
  geom_line()

ggplot(data = ca_np, aes(x = year, y = visitors)) +
  geom_line(aes(color = park_name, group = park_name))



```

